name: Node CI

on: [push]

jobs:
    quality:
        runs-on: ubuntu-latest
        env:
            CI: true
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: Run ESLint
              run: npm run lint
            - name: Run tests
              run: npm test -- --coverage --passWithNoTests
